django/hello-world/dynamicGreetings/urls.py
from . import views
from django.urls import path

# Kinda namespace of multiapp projects 
app_name = 'dynamicGreetings'
urlpatterns = [
    path('', views.index, name='index'),
    path('listSports', views.listSports, name='listSports'),
    path('editSport', views.editSport, name='editSport'),
    path('saveSport', views.saveSport, name='saveSport'),
    path('listCountries', views.listCountries, name='listCountries'),
    path('editCountry', views.editCountry, name='editCountry'),
    path('saveCountry', views.saveCountry, name='saveCountry'),
    path('listPersons', views.listPersons, name='listPersons'),
    path('editPerson', views.editPerson, name='editPerson'),
    path('savePerson', views.savePerson, name='savePerson')           
]

django/hello-world/helloWorld/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staticGreetings/', include('staticGreetings.urls')),
    path('dynamicGreetings/', include('dynamicGreetings.urls'))
]

django/hello-world/staticGreetings/urls.py
from . import views
from django.urls import path

# Kinda namespace of multiapp projects 
app_name = 'staticGreetings'
urlpatterns = [
    path('', views.index, name='index'),
    path('oldFashionedLink', views.oldFashionedLink, name='oldFashionedLink'),
    path('greetByName', views.greetByName, name='greetByName'),
    path('<str:name>/dynamicLink', views.dynamicLink, name='dynamicLink')
]

django/hello-world/dynamicGreetings/models.py
from django.db import models

      
class Country(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return  str(self.id) + ' ' + self.name  
        
class Sport(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return  str(self.id) + ' ' + self.name  

class Person(models.Model):
    name = models.CharField(max_length=200)
    dateBirth = models.DateTimeField('Birth date')
    nationalty = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    sports = models.ManyToManyField(Sport)
     
    def __str__(self):
        return str(self.id) + ' ' + self.name   

django/hello-world/staticGreetings/models.py
from django.db import models

# Create your models here.

django/hello-world/dynamicGreetings/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from .models import Country, Person, Sport

def index(request):
    template = loader.get_template('dynamicGreetings/index.html')
    context = {}
    return HttpResponse(template.render(context, request))   

def listSports(request):
    sports = Sport.objects.all()
    return render(request, 'dynamicGreetings/listSports.html', {'sports': sports})

def saveSport(request):
    sportName = request.POST.get('nameName')
    sportId = request.POST.get('nameHiddenId')
    if sportId == None:
        print('New sport name: ', sportName)
        newSport = Sport(name = sportName)
        newSport.save()
        print(newSport)
    else:
        sport = Sport.objects.get(pk=sportId)
        sport.name = sportName
        sport.save()
    return listSports(request)
    
def editSport(request):
    sportId = request.POST.get('nameHiddenId')
    sport = None
    if sportId != None:
        print('Sport id. to edit: ', str(sportId))
        sport = Sport.objects.get(pk=sportId)
        print('Sport to edit id: ', str(sport.id), ', name: ', sport.name)
    return render(request, 'dynamicGreetings/editSport.html', {'sport': sport})
    
def listCountries(request):
    countrys = Country.objects.all()
    return render(request, 'dynamicGreetings/listCountries.html', {'countries': countrys})

def saveCountry(request):
    countryName = request.POST.get('nameName')
    countryId = request.POST.get('nameHiddenId')
    if countryId == None:
        print('New country name: ', countryName)
        newCountry = Country(name = countryName)
        newCountry.save()
        print(newCountry)
    else:
        country = Country.objects.get(pk=countryId)
        country.name = countryName
        country.save()
    return listCountries(request)
    
def editCountry(request):
    countryId = request.POST.get('nameHiddenId')
    country = None
    if countryId != None:
        print('Country id. to edit: ', str(countryId))
        country = Country.objects.get(pk=countryId)
        print('Country to edit id: ', str(country.id), ', name: ', country.name)
    return render(request, 'dynamicGreetings/editCountry.html', {'country': country})
    
def listPersons(request):
    persons = Person.objects.all()
    return render(request, 'dynamicGreetings/listPersons.html', {'persons': persons})    
    
def savePerson(request):
    personName = request.POST.get('nameName')
    countryId = request.POST.get('countryId')
    birthDate = request.POST.get('dateBirth')
    personId = request.POST.get('nameHiddenId')
    if personId == None:
        print('New person name: ', personName)
        print('New person country id: ', countryId)
        print('New person birth date: ', birthDate)
        country = Country.objects.get(pk=countryId)
        print('New person nationality: ', country.name)
        newPerson = Person(name = personName, nationalty=country, dateBirth=birthDate)
        newPerson.save()
        print(newPerson)
    else:
        person = Person.objects.get(pk=personId)
        person.name = personName
        person.save()
    return listPersons(request)
    
def editPerson(request):
    personId = request.POST.get('nameHiddenId')
    person = None
    if personId != None:
        print('Person id. to edit: ', str(personId))
        person = Person.objects.get(pk=personId)
        print('Person to edit id: ', str(person.id), ', name: ', person.name)
    return render(request, 'dynamicGreetings/editPerson.html', {'person': person})
    

django/hello-world/staticGreetings/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse

def index(request):
    template = loader.get_template('staticGreetings/index.html')
    context = {}
    return HttpResponse(template.render(context, request))    

def oldFashionedLink(request):
    template = loader.get_template('staticGreetings/oldFashionedLink.html')
    context = {}
    return HttpResponse(template.render(context, request))    

def greetByName(request):
    template = loader.get_template('staticGreetings/greetByName.html')
    print('Form name: ' + str(request.POST.get('name')))
    context = {
        'name': request.POST.get('name')
    }
    return HttpResponse(template.render(context, request))    

def dynamicLink(request, name):
    template = loader.get_template('staticGreetings/greetByNameGET.html')
    context = {
        'name': name
    }
    return HttpResponse(template.render(context, request))       

django/hello-world/dynamicGreetings/templates/dynamicGreetings/editCountry.html
<h1>Edit Country</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'dynamicGreetings:saveCountry' %}" method="post">
{% csrf_token %}
    {% if country != None %}
        <input type="text" name="nameName" id="idName" value="{{ country.name }}">
        <input type="hidden" name="nameHiddenId" id="idHiddenId" value="{{ country.id}}">
    {% else %}
       <input type="text" name="nameName" id="idName" value="<Country name>">
    {% endif %}
    <input type="submit" value="Save">
</form>

django/hello-world/dynamicGreetings/templates/dynamicGreetings/editPerson.html
<h1>Edit Person</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'dynamicGreetings:savePerson' %}" method="post">
{% csrf_token %}
    {% if person != None %}
        <input type="text" name="nameName" id="idName" value="{{ person.name }}">
        <input type="text" name="countryId" id="countryId" value="{{ person.nationalty.id }}">
        <input type="text" name="dateBirth" id="dateBirth" value="{{ person.dateBirth }}">
        <input type="hidden" name="nameHiddenId" id="idHiddenId" value="{{ person.id}}">
    {% else %}
       <input type="text" name="nameName" id="idName" value="<Person name>">
       <input type="text" name="countryId" id="countryId" value="< Country >">
       <input type="text" name="dateBirth" id="dateBirth" value="< Birth date >">
    {% endif %}
    <input type="submit" value="Save">
</form>

django/hello-world/dynamicGreetings/templates/dynamicGreetings/editSport.html
<h1>Edit Sport</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'dynamicGreetings:saveSport' %}" method="post">
{% csrf_token %}
    {% if sport != None %}
        <input type="text" name="nameName" id="idName" value="{{ sport.name }}">
        <input type="hidden" name="nameHiddenId" id="idHiddenId" value="{{ sport.id}}">
    {% else %}
       <input type="text" name="nameName" id="idName" value="<Sport name>">
    {% endif %}
    <input type="submit" value="Save">
</form>

django/hello-world/dynamicGreetings/templates/dynamicGreetings/index.html
<br>    
<h2>Hello world!</h2>
<p>Rejoice my fellow users... Now we can greet and remember... </p>
<p><a href="{% url 'dynamicGreetings:listCountries' %}">Countries</a></p>
<p><a href="{% url 'dynamicGreetings:listPersons' %}">Persons</a></p>
<p><a href="{% url 'dynamicGreetings:listSports' %}">Sports</a></p>

django/hello-world/dynamicGreetings/templates/dynamicGreetings/listCountries.html
<style type="text/css" media="screen">
.columnId {
  float: left;
  width: 3%;
}

.columnName {
  float: left;
  width: 20%;
}

.columnButton {
  float: left;
  width: 3%;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>

<h1>Countries</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<ul>
    <li><a href="{% url 'dynamicGreetings:editCountry' %}">New country</a></li>
{% for country in countries %}
    <li>
        <form action="{% url 'dynamicGreetings:editCountry' %}" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="columnId">{{ country.id }}</div>
              <div class="columnName">{{ country.name }}</div>
              <div class="columnButton">
                  <input type="hidden" name="nameHiddenId" id="idHiddenId" value="{{ country.id}}">
                  <input type="submit" value="Edit">
              </div>
            </div> 
        </form>
    </li>
{% endfor %}
 <li><a href="{% url 'dynamicGreetings:index' %}">Main</a></li>
</ul>

django/hello-world/dynamicGreetings/templates/dynamicGreetings/listPersons.html
<style type="text/css" media="screen">
.columnId {
  float: left;
  width: 3%;
}

.columnName {
  float: left;
  width: 20%;
}

.columnButton {
  float: left;
  width: 3%;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>

<h1>Persons</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<ul>
    <li><a href="{% url 'dynamicGreetings:editPerson' %}">New person</a></li>
{% for person in persons %}
    <li>
        <form action="{% url 'dynamicGreetings:editPerson' %}" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="columnId">{{ person.id }}</div>
              <div class="columnName">{{ person.name }}</div>
              <div class="columnName">{{ person.nationalty.name }}</div>
              <div class="columnName">{{ person.dateBirth }}</div>
              <div class="columnButton">
                  <input type="hidden" name="nameHiddenId" id="idHiddenId" value="{{ person.id}}">
                  <input type="submit" value="Edit">
              </div>
            </div> 
        </form>
    </li>
{% endfor %}
 <li><a href="{% url 'dynamicGreetings:index' %}">Main</a></li>
</ul>

django/hello-world/dynamicGreetings/templates/dynamicGreetings/listSports.html
<style type="text/css" media="screen">
.columnId {
  float: left;
  width: 3%;
}

.columnName {
  float: left;
  width: 20%;
}

.columnButton {
  float: left;
  width: 3%;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>

<h1>Sports</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<ul>
    <li><a href="{% url 'dynamicGreetings:editSport' %}">New sport</a></li>
{% for sport in sports %}
    <li>
        <form action="{% url 'dynamicGreetings:editSport' %}" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="columnId">{{ sport.id }}</div>
              <div class="columnName">{{ sport.name }}</div>
              <div class="columnButton">
                  <input type="hidden" name="nameHiddenId" id="idHiddenId" value="{{ sport.id}}">
                  <input type="submit" value="Edit">
              </div>
            </div> 
        </form>
    </li>
{% endfor %}
    <li><a href="{% url 'dynamicGreetings:index' %}">Main</a></li>
</ul>

django/hello-world/staticGreetings/templates/staticGreetings/cheers.html
<h2>I'm glad you identify as {{ gender }}!!</h2>
<br>
<p>In any case you are MALE or FEMALE</p>
<a href="{% url 'staticGreetings:index' %}">This is an old fashioned link  to get you back to the index</a>

django/hello-world/staticGreetings/templates/staticGreetings/greetByName.html
<h2>Welcome {{ name }}!!</h2>
<br>
<p>We are glad you came here by POST.</p>
<a href="{% url 'staticGreetings:index' %}">This is an old fashioned link  to get you back to the index</a>
<br>
<a href="{% url 'staticGreetings:dynamicLink' name %}">Greet by GET</a>

django/hello-world/staticGreetings/templates/staticGreetings/greetByNameGET.html
<h2>Welcome {{ name }}!!</h2>
<br>
<p>We are glad you came here by GET.</p>
<a href="{% url 'staticGreetings:index' %}">This is an old fashioned link  to get you back to the index</a>

django/hello-world/staticGreetings/templates/staticGreetings/index.html
<h2>Hello world!</h2>
<br>
<a href="{% url 'staticGreetings:oldFashionedLink' %}">This is an old fashioned link</a>
<br><br>
<form action="{% url 'staticGreetings:greetByName' %}" method="post">
{% csrf_token %}
    <label for="name">Please introduce your name:</label>
    <input type="text" name="name" id="name">
    <input type="submit" value="Greet by POST">
</form>

django/hello-world/staticGreetings/templates/staticGreetings/oldFashionedLink.html
<h2>Welcome whoever came through the old fashioned link!!</h2>
<br>
<a href="{% url 'staticGreetings:index' %}">This is an old fashioned link  to get you back to the index</a>